{"name": "Ошибка аутентификации курьера при вводе невалидных данных", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 404 and {'code': 404,...ь не найдена'} == {'message': '...ь не найдена'}\n +  where 404 = <Response [404]>.status_code\n  \n  Omitting 1 identical items, use -vv to show\n  Left contains 1 more item:\n  \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mcode\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[94m404\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\n  Use -v to get more diff)", "trace": "self = <test_courier_login.TestCourierLogin object at 0x0000027605918DA0>, nonexistent_credentials = {'login': 'Six.585', 'password': 'p1P$6HhV*C'}\n\n    @allure.title('Ошибка аутентификации курьера при вводе невалидных данных')\n    @allure.description('В тест по очереди передаются наборы данных с несуществующим логином или неверным паролем. '\n                        'Проверяются код и тело ответа.')\n    @pytest.mark.parametrize('nonexistent_credentials', [\n        {'login': create_random_login(), 'password': create_random_password()},\n        Data.courier_data_with_wrong_password\n    ])\n    def test_courier_login_nonexistent_data_not_found(self, nonexistent_credentials):\n        response = requests.post(Urls.URL_courier_login, data=nonexistent_credentials)\n>       assert response.status_code == 404 and response.json() == {'message': 'Учетная запись не найдена'}\nE       AssertionError: assert (404 == 404 and {'code': 404,...ь не найдена'} == {'message': '...ь не найдена'}\nE        +  where 404 = <Response [404]>.status_code\nE         \nE         Omitting 1 identical items, use -vv to show\nE         Left contains 1 more item:\nE         \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mcode\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[94m404\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\nE         Use -v to get more diff)\n\ntests\\test_courier_login.py:26: AssertionError"}, "description": "В тест по очереди передаются наборы данных с несуществующим логином или неверным паролем. Проверяются код и тело ответа.", "parameters": [{"name": "nonexistent_credentials", "value": "{'login': 'Six.585', 'password': 'p1P$6HhV*C'}"}], "start": 1742320156628, "stop": 1742320156735, "uuid": "cb76c58c-da72-4a16-a5e0-79bd7da8e9d3", "historyId": "c87f76e0c3bce7807ede1f4d3f267cd6", "testCaseId": "199be2f2af7455b14ed4795a4ee970da", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_login_nonexistent_data_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-JHHR6FB"}, {"name": "thread", "value": "1556-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}